### ISSUE TITLE
Codes for Fig 1.a

### ISSUE THREAD

**Issue by TongLiu-github** [bdy9527/FAGCN#2]
I think this work is very important for our research now. But it will be very nice of you to upload your codes for Fig. 1(a), which should be easy to reproduce. 
Thanks for your reply.

**Comment by jiaruHithub** [comment]
同样期待您可以上传图1中信号频率相关图代码，感谢。

**Comment by bdy9527** [comment]
A new file synthetic.py has been updated.

Hope this can help you.
